---

hamiltonian:
  num_rotor: 3
  vertex_weight: 5.0
  edges:
  - j: 0
    k: 1
    beta: 1.0
  - j: 1
    k: 2
    beta: 1.0

rbm:
  num_hidden: 15
  init_bias_range: 1.0
  init_weight_std: 0.33333333333333331 # sqrt(2 / (3 + 15))

metropolis:
  num_steps: 18000
  warm_steps: 3000
  cherry_pick: 15
  bump_size: 3.5

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

output:
  prefix: "runs/chain_3_vmc"
  frequency: 1000
  model: true
  samples: true
