---

hamiltonian: runs/chain_7_hamiltonian.yaml

rbm:
  num_hidden: 35

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

metropolis:
  num_steps: 7000
  warm_steps: 3500
  cherry_pick: 1
  bump_size: 3.5

logging:
  stdout_frequency: 100
