---

hamiltonian: "runs/chain_2_hamiltonian.yaml"

rbm:
  num_hidden: 10

metropolis:
  num_steps: 12000
  warm_steps: 2000
  cherry_pick: 10
  bump_size: 3.5

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

output:
  prefix: "runs/chain_2_vmc"
  frequency: 1000
  model: true
  samples: true
