---

hamiltonian: "runs/chain_5_hamiltonian.yaml"

rbm:
  num_hidden: 25

metropolis:
  num_steps: 30000
  warm_steps: 5000
  cherry_pick: 25
  bump_size: 3.5

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

output:
  prefix: "runs/chain_5_vmc"
  frequency: 1000
  model: true
  samples: true
