---

hamiltonian: "runs/chain_10_hamiltonian.yaml"

rbm:
  num_hidden: 80
  init_bias_range: 1.0
  init_weight_std: 1.0

metropolis:
  num_steps: 120000
  warm_steps: 20000
  cherry_pick: 100
  bump_size: 2.0

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-03

output:
  prefix: "runs/chain_10_vmc_4"
  frequency: 1000
  model: true
  samples: true
