---

hamiltonian: "runs/chain_6_hamiltonian.yaml"

rbm:
  num_hidden: 30

metropolis:
  num_steps: 36000
  warm_steps: 6000
  cherry_pick: 30
  bump_size: 3.5

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

output:
  prefix: "runs/chain_6_vmc"
  frequency: 1000
  model: true
  samples: true
