---

hamiltonian: "runs/chain_7_hamiltonian.yaml"

rbm:
  num_hidden: 35

metropolis:
  num_steps: 42000
  warm_steps: 7000
  cherry_pick: 35
  bump_size: 3.5

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

output:
  prefix: "runs/chain_7_vmc"
  frequency: 1000
  model: true
  samples: true
