---

hamiltonian: "runs/chain_3_hamiltonian.yaml"

rbm:
  num_hidden: 15

metropolis:
  num_steps: 18000
  warm_steps: 3000
  cherry_pick: 15
  bump_size: 3.5

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

output:
  prefix: "runs/chain_3_vmc"
  frequency: 1000
  model: true
  samples: true
