---

hamiltonian: runs/chain_6_hamiltonian.yaml

rbm:
  num_hidden: 30

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

metropolis:
  num_steps: 6000
  warm_steps: 3000
  cherry_pick: 1
  bump_size: 3.5

logging:
  stdout_frequency: 100
