---

hamiltonian: hamiltonian.yaml

rbm:
  num_hidden: 8

gradient_descent:
  num_steps: 1000
  lr: 1.0e-03

stoch_reconfig:
  sr_reg: 1.0e-09

metropolis:
  num_steps: 500
  warm_steps: 250
  cherry_pick: 1
  bump_size: 3.5

logging:
  stdout_frequency: 10
