---

# output directory
logdir: './logs/'

# RBM parameters
num_visible: 2
num_hidden: 8

# Hamiltonian is given by
#
#   H = - \frac{h}{2} \sum_{j = 1}^d \frac{\partial^2}{\partial \theta_j^2}
#       + \sum_{(j, k) \in E} (1 -2 * \beta_{jk} \cos(\theta_j - \theta_k))
#
# In network specifications, edges are specified by the boundary nodes (j, k)
# and interaction strength G_jk
#
# The following specification represents the graph:
#
#   0 - 1
#
h: 5.0
edges:
- j: 0
  k: 1
  beta: 1.0

# Gradient descent parmeters
num_step: 2500
lr: 1.0e-03

# SR parameters
sr_reg: 1.0e-09

# Metropolis parameters
metropolis_steps: 500
bump_size: 3.5
warm_steps: 250
