---

hamiltonian:
  num_rotor: 6
  vertex_weight: 5.0
  edges:
  - j: 0
    k: 1
    beta: 1.0
  - j: 1
    k: 2
    beta: 1.0
  - j: 2
    k: 3
    beta: 1.0
  - j: 3
    k: 4
    beta: 1.0
  - j: 4
    k: 5
    beta: 1.0

rbm:
  num_hidden: 30
  init_bias_range: 1.0
  init_weight_std: 0.23570226039551584 # sqrt(2 / (6 + 30))

metropolis:
  num_steps: 36000
  warm_steps: 6000
  cherry_pick: 30
  bump_size: 3.5

gradient_descent:
  num_steps: 10000
  lr: 1.0e-02

stoch_reconfig:
  sr_reg: 1.0e-06

output:
  prefix: "runs/chain_6_vmc"
  frequency: 1000
  model: true
  samples: true
